# Generated by Django 5.0.3 on 2024-03-26 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemlistings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categoryID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='categoryID', to='itemlistings.main'),
        ),
    ]
