# Generated by Django 5.0.3 on 2024-03-26 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemlistings', '0002_alter_category_categoryid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='id',
        ),
        migrations.AddField(
            model_name='main',
            name='categoryID',
            field=models.ForeignKey(db_column='categoryID', default=4, on_delete=django.db.models.deletion.RESTRICT, related_name='items', to='itemlistings.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='categoryID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
