INSERT INTO tocd.itemlistings_main (`itemID`,`itemName`,`Distributer`,`imagepath`,`categoryID`,`price`,`manufacture`)
VALUES
(1,'Cream crackers','Distributer','/image.jpg',1,3.99,'Excelsior'),
(2,'Water crackers','Distributer','/image.jpg',1,3.99,'Excelsior'),
(3,'Big foot','Distributer','/image.jpg',1,3.99,'Excelsior'),
(4,'Exotica','Distributer','/image.jpg',1,3.99,'Excelsior'),
(5,'Tortillaz','Distributer','/image.jpg',1,3.99,'Excelsior'),
(6,'Soldanza','Distributer','/image.jpg',1,3.99,'Excelsior'),
(7,'Fun C','Distributer','/image.jpg',1,3.99,'Excelsior'),
(8,'Shirley','Distributer','/image.jpg',1,3.99,'Excelsior'),
(9,'Snackers','Distributer','/image.jpg',1,3.99,'Excelsior'),
(10,'Cheese Krunchies','Distributer','/image.jpg',1,3.99,'Excelsior'),
(11,'chocolate chips','Distributer','/image.jpg',1,3.99,'Excelsior'),
(12,'Chick N chips','Distributer','/image.jpg',1,3.99,'Excelsior'),
(13,'Peanuts (Variety)','Distributer','/image.jpg',1,3.99,'Excelsior'),
(14,'Sweet Tea','Distributer','/image.jpg',1,3.99,'Excelsior'),
(15,'Wheat biscuits','Distributer','/image.jpg',1,3.99,'Excelsior'),
(16,'Double Cheese','Distributer','/image.jpg',1,3.99,'Excelsior'),
(17,'Coconut cookies','Distributer','/image.jpg',1,3.99,'Excelsior'),
(18,'Cream crackers','Distributer','/image.jpg',1,3.99,'National'),
(19,'Ovaltine','Distributer','/image.jpg',1,3.99,'None'),
(20,'Rough tops','Distributer','/image.jpg',1,3.99,'None'),
(21,'Evaporated milk','Distributer','/image.jpg',1,3.99,'Nestle'),
(22,'Round spice bun','Distributer','/image.jpg',1,3.99,'National'),
(23,'12 oz loaf spice bun','Distributer','/image.jpg',1,3.99,'National'),
(24,'Duplex sandwich cookies','Distributer','/image.jpg',1,3.99,'National'),
(25,'Peanut butter Sandwich cookies','Distributer','/image.jpg',1,3.99,'National'),
(26,'Strawberry sandwich cookies','Distributer','/image.jpg',1,3.99,'National'),
(27,'Tea biscuit','Distributer','/image.jpg',1,3.99,'National'),
(28,'Ginger tea biscuit','Distributer','/image.jpg',1,3.99,'National'),
(29,'Cheese curls','Distributer','/image.jpg',1,3.99,'National'),
(30,'Zesty cheese popcorn','Distributer','/image.jpg',1,3.99,'National'),
(31,'Tigers','Distributer','/image.jpg',1,3.99,'None'),
(32,'Sugar balls','Distributer','/image.jpg',1,3.99,'None'),
(33,'Yolo','Distributer','/image.jpg',1,3.99,'Excelsior'),
(34,'Jumbies','Distributer','/image.jpg',1,3.99,'Excelsior'),
(35,'Tea time','Distributer','/image.jpg',1,3.99,'Excelsior'),
(36,'Yellow Yam','Distributer','/image.jpg',2,3.99,'None'),
(37,'Yellow Yam','Distributer','/image.jpg',2,3.99,'None'),
(38,'White yam','Distributer','/image.jpg',2,3.99,'None'),
(39,'Cho Cho','Distributer','/image.jpg',2,3.99,'None'),
(40,'Dasheen','Distributer','/image.jpg',2,3.99,'None'),
(41,'Green Banana','Distributer','/image.jpg',2,3.99,'None'),
(42,'Green plantain','Distributer','/image.jpg',2,3.99,'None'),
(43,'Riple plantain','Distributer','/image.jpg',2,3.99,'None'),
(44,'Sweet Potato','Distributer','/image.jpg',2,3.99,'None'),
(45,'Irish Potato','Distributer','/image.jpg',2,3.99,'None'),
(46,'Bread Fruit','Distributer','/image.jpg',2,3.99,'None'),
(47,'Pumpkin','Distributer','/image.jpg',2,3.99,'None'),
(48,'Escellion','Distributer','/image.jpg',2,3.99,'None'),
(49,'Thyme','Distributer','/image.jpg',2,3.99,'None'),
(50,'Onion','Distributer','/image.jpg',2,3.99,'None'),
(51,'Scotch Bonnet Pepper','Distributer','/image.jpg',2,3.99,'None'),
(52,'Sweet Pepper','Distributer','/image.jpg',2,3.99,'None'),
(53,'Baked beans','Distributer','/image.jpg',3,3.99,'Grace'),
(54,'Sausages','Distributer','/image.jpg',3,3.99,'Grace'),
(55,'Tin Mackerel in hot tomato sauce','Distributer','/image.jpg',3,3.99,'Grace'),
(56,'Coconut Milk','Distributer','/image.jpg',3,3.99,'Grace'),
(57,'Chick peas','Distributer','/image.jpg',3,3.99,'Grace'),
(58,'Butter bean','Distributer','/image.jpg',3,3.99,'Grace'),
(59,'Tuna','Distributer','/image.jpg',3,3.99,'Grace'),
(60,'Corned beef','Distributer','/image.jpg',3,3.99,'Grace'),
(61,'Green peas','Distributer','/image.jpg',3,3.99,'Grace'),
(62,'Tin Mackerel in tomato sauce','Distributer','/image.jpg',3,3.99,'Grace'),
(63,'Mixed Vegetables','Distributer','/image.jpg',3,3.99,'Grace'),
(64,'Red kidney peas','Distributer','/image.jpg',3,3.99,'Grace'),
(65,'Sardines in vegetable oil','Distributer','/image.jpg',3,3.99,'Grace'),
(66,'sardines with peppers in vegetable oil','Distributer','/image.jpg',3,3.99,'Grace'),
(67,'whole kernel sweet corn','Distributer','/image.jpg',3,3.99,'Grace'),
(68,'Broad bean','Distributer','/image.jpg',3,3.99,'Grace'),
(69,'Instant porridge cornmeal','Distributer','/image.jpg',4,3.99,'Grace'),
(70,'Instant porridge banana','Distributer','/image.jpg',4,3.99,'Grace'),
(71,'Chicken flavour soup mix','Distributer','/image.jpg',4,3.99,'Grace'),
(72,'Chicken frankfurters','Distributer','/image.jpg',4,3.99,'Grace'),
(73,'Cock flavoured soup mix','Distributer','/image.jpg',4,3.99,'Grace'),
(74,'Coconut milk powder','Distributer','/image.jpg',4,3.99,'Grace'),
(75,'Browning','Distributer','/image.jpg',4,3.99,'Grace'),
(76,'Instant porridge oats','Distributer','/image.jpg',4,3.99,'Grace'),
(77,'Vinegar','Distributer','/image.jpg',4,3.99,'Grace'),
(78,'Fish and meat sauce','Distributer','/image.jpg',4,3.99,'Grace'),
(79,'Fish tea soup mix','Distributer','/image.jpg',4,3.99,'Grace'),
(80,'Bammy','Distributer','/image.jpg',4,3.99,'None'),
(81,'Hot pepper sauce','Distributer','/image.jpg',4,3.99,'Grace'),
(82,'Tomato Ketchup','Distributer','/image.jpg',4,3.99,'Grace'),
(83,'Kola champagne syrup','Distributer','/image.jpg',4,3.99,'Grace'),
(84,'Long grain white rice','Distributer','/image.jpg',4,3.99,'Grace'),
(85,'Parboiled rice','Distributer','/image.jpg',4,3.99,'Grace'),
(86,'Coconut oil','Distributer','/image.jpg',4,3.99,'Grace'),
(87,'Pumpkin flavour soup mix','Distributer','/image.jpg',4,3.99,'Grace'),
(88,'Original bbq sauce','Distributer','/image.jpg',4,3.99,'Kraft'),
(89,'Sweet and spicy bbq sauce','Distributer','/image.jpg',4,3.99,'Kraft'),
(90,'sweet brown sugar bbq sauce','Distributer','/image.jpg',4,3.99,'Kraft'),
(91,'Mayo','Distributer','/image.jpg',4,3.99,'Kraft'),
(92,'Indian Girl corn meal','Distributer','/image.jpg',4,3.99,'None'),
(93,'Scotch bonnet pepper sauce','Distributer','/image.jpg',5,3.99,'Grace'),
(94,'Scotch bonnet pepper sauce','Distributer','/image.jpg',5,3.99,'Grace'),
(95,'Scotch bonnet pepper sauce','Distributer','/image.jpg',5,3.99,'Grace'),
(96,'All Purpose seasoning','Distributer','/image.jpg',5,3.99,'Grace'),
(97,'Chicken Seasoning','Distributer','/image.jpg',5,3.99,'Grace'),
(98,'Fish Seasoning','Distributer','/image.jpg',5,3.99,'Grace'),
(99,'Garlic powder','Distributer','/image.jpg',5,3.99,'Grace'),
(100,'Onion Powder','Distributer','/image.jpg',5,3.99,'Grace'),
(101,'Ginger, garlic and pimento se.','Distributer','/image.jpg',5,3.99,'Grace'),
(102,'Jerk seasoning','Distributer','/image.jpg',5,3.99,'Grace'),
(103,'Oxtail seasoning','Distributer','/image.jpg',5,3.99,'Grace'),
(104,'Jamaican jerk seasoning sauce hot and spicy','Distributer','/image.jpg',5,3.99,'Grace'),
(105,'Jamaican jerk seasoning sauce mild','Distributer','/image.jpg',5,3.99,'Grace'),
(106,'Jamaican jerk bbq sauce','Distributer','/image.jpg',5,3.99,'Grace'),
(107,'Jerk seasoning','Distributer','/image.jpg',5,3.99,'maggie'),
(108,'Chicken Seasoning','Distributer','/image.jpg',5,3.99,'Maggie'),
(109,'All Purpose seasoning','Distributer','/image.jpg',5,3.99,'Maggie'),
(110,'Beta pac Curry','Distributer','/image.jpg',5,3.99,'None'),
(111,'Maggie cubes','Distributer','/image.jpg',5,3.99,'maggie'),
(112,'Aloe Vera Drink','Distributer','/image.jpg',7,3.99,'Grace'),
(113,'Carrot drink (tin)','Distributer','/image.jpg',7,3.99,'Grace'),
(114,'Cherry Syrup','Distributer','/image.jpg',7,3.99,'Grace'),
(115,'Grace fresh start berry','Distributer','/image.jpg',7,3.99,'Grace'),
(116,'Grace fresh start citrus punch','Distributer','/image.jpg',7,3.99,'Grace'),
(117,'Grace fresh start fruit punch','Distributer','/image.jpg',7,3.99,'Grace'),
(118,'Grace fresh start grape','Distributer','/image.jpg',7,3.99,'Grace'),
(119,'Grace fresh start lemonade','Distributer','/image.jpg',7,3.99,'Grace'),
(120,'Grace fresh start pineapple kiwi','Distributer','/image.jpg',7,3.99,'Grace'),
(121,'Grace fresh start orange','Distributer','/image.jpg',7,3.99,'Grace'),
(122,'Grace fresh start mango','Distributer','/image.jpg',7,3.99,'Grace'),
(123,'Grace fresh start peach mania','Distributer','/image.jpg',7,3.99,'Grace'),
(124,'Grace fresh start mango carrot','Distributer','/image.jpg',7,3.99,'Grace'),
(125,'Grace fresh start strawberry passion','Distributer','/image.jpg',7,3.99,'Grace'),
(126,'Fruit punch syrup','Distributer','/image.jpg',7,3.99,'Grace'),
(127,'Ginger lemon tea','Distributer','/image.jpg',7,3.99,'Grace'),
(128,'Ginger mint tea','Distributer','/image.jpg',7,3.99,'Grace'),
(129,'Ginger tea','Distributer','/image.jpg',7,3.99,'Grace'),
(130,'Pineapple cherry drink (tin)','Distributer','/image.jpg',7,3.99,'Grace'),
(131,'Pineapple juice (tin)','Distributer','/image.jpg',7,3.99,'Grace'),
(132,'Fruit punch juice (tin)','Distributer','/image.jpg',7,3.99,'Grace'),
(133,'Pineapple orange syrup','Distributer','/image.jpg',7,3.99,'Grace'),
(134,'Tropical rhythm Guava carrot','Distributer','/image.jpg',7,3.99,'Grace'),
(135,'Tropical rhythm island mango','Distributer','/image.jpg',7,3.99,'Grace'),
(136,'Tropical rhythm fruit punch','Distributer','/image.jpg',7,3.99,'Grace'),
(137,'Tropical rhythm june plum','Distributer','/image.jpg',7,3.99,'Grace'),
(138,'Tropical rhythm lychee paradise','Distributer','/image.jpg',7,3.99,'Grace'),
(139,'Tropical rhythm mango carrot','Distributer','/image.jpg',7,3.99,'Grace'),
(140,'Tropical rhythm pineapple and ginger','Distributer','/image.jpg',7,3.99,'Grace'),
(141,'Tropical rhythm reggae medley','Distributer','/image.jpg',7,3.99,'Grace'),
(142,'Tropical rhythm sorrel and ginger','Distributer','/image.jpg',7,3.99,'Grace'),
(143,'Roma instant cocoa mix ht chocolate','Distributer','/image.jpg',7,3.99,'Grace'),
(144,'Big Bamboo Jamaican Irish moss drink','Distributer','/image.jpg',7,3.99,'None'),
(145,'Chubby','Distributer','/image.jpg',7,3.99,'None'),
(146,'Ginger beer','Distributer','/image.jpg',7,3.99,'None'),
(147,'Pepsi','Distributer','/image.jpg',7,3.99,'None'),
(148,'Ting','Distributer','/image.jpg',7,3.99,'None'),
(149,'Bigga','Distributer','/image.jpg',7,3.99,'None'),
(150,'Apple J','Distributer','/image.jpg',7,3.99,'None'),
(151,'Pear J','Distributer','/image.jpg',7,3.99,'None'),
(152,'Vita malt','Distributer','/image.jpg',7,3.99,'None'),
(153,'Boom','Distributer','/image.jpg',7,3.99,'None'),
(154,'Dried Sorrel','Distributer','/image.jpg',7,3.99,'None'),
(155,'Natural irish moss','Distributer','/image.jpg',7,3.99,'None'),
(156,'Milo','Distributer','/image.jpg',7,3.99,'None'),
(157,'Mint','Distributer','/image.jpg',7,3.99,'None'),
(158,'Cerasee','Distributer','/image.jpg',7,3.99,'None'),
(159,'Pig''s tail','Distributer','/image.jpg',6,3.99,'None'),
(160,'oxtail','Distributer','/image.jpg',6,3.99,'None'),
(161,'cow foot','Distributer','/image.jpg',6,3.99,'None'),
(162,'chicken foot','Distributer','/image.jpg',6,3.99,'None'),
(163,'Mutton','Distributer','/image.jpg',6,3.99,'None'),
(164,'Beef','Distributer','/image.jpg',6,3.99,'None'),
(165,'Pork','Distributer','/image.jpg',6,3.99,'None'),
(166,'Corn pork','Distributer','/image.jpg',6,3.99,'None'),
(167,'Salfish','Distributer','/image.jpg',6,3.99,'None'),
(168,'Salt Mackerl','Distributer','/image.jpg',6,3.99,'None');
